name: medv1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.2.1
  - pandas=2.2.1
  - pickleshare=0.7.5
  - pip=23.3.1
  - pre-commit=3.4.0
  - pydicom=2.4.4
  - pytest=7.4.0
  - python=3.12.2
  - pytorch=2.2.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - stack_data=0.6.2
  - sympy=1.12
  - tornado=6.3.3
  - tqdm=4.65.0
  - virtualenv=20.24.1
  - yaml=0.2.5
